import LegalPageLayout, { LegalSection } from "../components/layout/LegalPageLayout";

const Terms = () => (
  <LegalPageLayout title="TERMS OF SERVICE" updated="19 September 2026">
    <p>
      These Terms govern your use of the TeenRaah website and app and any purchase you make through it. By
      creating an account or placing an order, you agree to these Terms.
    </p>

    <LegalSection heading="Accounts">
      <p>
        You must provide accurate information when creating an account and verify your email address before
        placing an order. You're responsible for keeping your password confidential and for all activity
        under your account.
      </p>
    </LegalSection>

    <LegalSection heading="Orders & Pricing">
      <ul className="list-disc ml-5 space-y-1">
        <li>All prices are listed in Indian Rupees (₹) and include applicable taxes unless stated otherwise</li>
        <li>We reserve the right to correct pricing or listing errors, and to cancel and refund an order affected by one</li>
        <li>An order is confirmed once payment is successfully captured by Razorpay</li>
        <li>In rare cases of a stock conflict (two customers ordering the last unit at the same moment), we'll contact you promptly to offer a refund or a suitable alternative</li>
      </ul>
    </LegalSection>

    <LegalSection heading="Payments">
      <p>
        Payments are processed securely by Razorpay. TeenRaah does not store your card, UPI, or net-banking
        credentials at any point.
      </p>
    </LegalSection>

    <LegalSection heading="Coupons, Referrals & Wallet Credit">
      <p>
        Coupon codes are subject to the terms shown at the time of use (minimum order value, expiry, usage
        limits) and can be withdrawn or modified at any time. Referral and wallet rewards are credited once
        the qualifying order is confirmed and are non-transferable and have no cash value outside TeenRaah.
      </p>
    </LegalSection>

    <LegalSection heading="Reviews">
      <p>
        Product reviews may only be submitted by customers with a delivered order for that product. Reviews
        must be your own genuine experience — we may remove reviews that are abusive, spam, or clearly
        unrelated to the product, without notice.
      </p>
    </LegalSection>

    <LegalSection heading="The TeenRaah Assistant & AI Image Generation">
      <p>
        The chatbot is an automated assistant and can make mistakes — always confirm order details, pricing,
        and policies against the relevant page before relying on its answers. AI-generated concept images are
        illustrative only and may not exactly match the final product; they are limited to bag and travel-gear
        concepts and subject to a daily generation limit per account.
      </p>
    </LegalSection>

    <LegalSection heading="Limitation of Liability">
      <p>
        TeenRaah is not liable for indirect or consequential losses arising from use of the site, delays
        outside our reasonable control, or content generated by the AI assistant. Nothing here limits any
        right you have under Indian consumer protection law that cannot be excluded.
      </p>
    </LegalSection>

    <LegalSection heading="Governing Law">
      <p>These Terms are governed by the laws of India, and disputes are subject to the jurisdiction of the courts of India.</p>
    </LegalSection>

    <p className="text-xs text-stone pt-6 border-t border-ink/8">
      This is a template and should be reviewed by a qualified professional before you rely on it for a live
      store — it isn't legal advice.
    </p>
  </LegalPageLayout>
);

export default Terms;
